### ISSUE TITLE
Messed up project

### ISSUE THREAD

**Issue by AdrianVovk** [claucookie/mini-equalizer-library-android#5]
Once I tried this library, my app wouldn't build, In the messages window it mentioned the android manifest. Please fix this I would love to use this.

**Comment by claucookie** [comment]
Could you give me more information about the error message and what other libraries are you using? I will update it as soon as possible.

**Comment by AdrianVovk** [comment]
@claucookie it was Manifest entry already defined   or something like that. Don't have access to a computer for now. You can see all the code at github.com/Substance-Project/GEM
